/**
 * Renders every template with the design board's sample data into out/ (open
 * out/index.html), and regenerates the Supabase sign-in template in supabase/.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import * as f from "../src/fixtures.js";
import {
  alertEmail,
  recommendationEmail,
  signInCodeEmail,
  supabaseSignInTemplate,
  waitlistEmail,
  weekDigestEmail,
  youreInEmail,
  type Email,
} from "../src/index.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "out");
mkdirSync(out, { recursive: true });

export const SUPABASE_EXPIRY_MINUTES = 10;

const emails: Record<string, Email> = {
  "sign-in-code": signInCodeEmail(f.signIn),
  "week-one-thing": weekDigestEmail(f.weekOneThing),
  "week-quiet": weekDigestEmail(f.weekQuiet),
  "week-four-things": weekDigestEmail(f.weekFourThings),
  "week-missing-pot": weekDigestEmail(f.weekMissingPot),
  "week-stale-prices": weekDigestEmail(f.weekStalePrices),
  "alert-limit-80": alertEmail(f.alertLimit80),
  "alert-cap-by-growth": alertEmail(f.alertCapByGrowth),
  "alert-urgent-move": alertEmail(f.alertUrgentMove),
  "alert-push-stopped": alertEmail(f.alertPushStopped),
  recommendation: recommendationEmail(f.recommendationAlone),
  waitlist: waitlistEmail(f.waitlist),
  "youre-in": youreInEmail(f.youreIn),
};

const links: string[] = [];
for (const [name, email] of Object.entries(emails)) {
  writeFileSync(join(out, `${name}.html`), email.html);
  writeFileSync(
    join(out, `${name}.txt`),
    `Subject: ${email.subject}\nPreheader: ${email.preheader}\n\n${email.text}`,
  );
  links.push(
    `<li><a href="${name}.html">${name}</a> · <a href="${name}.txt">text</a> — ${email.subject}</li>`,
  );
}
writeFileSync(
  join(out, "index.html"),
  `<!DOCTYPE html><meta charset="utf-8"><title>Pip emails</title><ul style="font:15px/1.8 system-ui">${links.join("")}</ul>`,
);

const supabase = supabaseSignInTemplate(SUPABASE_EXPIRY_MINUTES);
const header = `<!--
  GENERATED by packages/emails (pnpm --filter @finance-app/emails preview). Don't edit by hand.
  Supabase → Authentication → Emails → Templates → "Magic Link".
  Subject: ${supabase.subject}
  Needs: Email OTP Expiration = ${SUPABASE_EXPIRY_MINUTES * 60} seconds, Email OTP Length = 8.
-->
`;
writeFileSync(join(root, "supabase", "sign-in-code.html"), header + supabase.html);
writeFileSync(join(root, "supabase", "sign-in-code.subject.txt"), `${supabase.subject}\n`);
console.log(
  `Wrote ${Object.keys(emails).length} emails to ${out} and the Supabase template to supabase/.`,
);
